extends Path3D

#Core functionalityGenerated by chatgpt -
#Given prompt "Make me a script to generate a hilbert curve along a path3d on the XZ plane"

@export var order: int = 4   # Hilbert curve order (higher = more complex)
@export var size: float = 100.0  # Scale of each segment
@export var chamfer_size: float = .2
@export var save_path = "res://hilbert_curve.tres"

func _ready():
	var first_pass_points = hilbert2d_points(order)
	var points = chamfer_points(first_pass_points, chamfer_size)
	var curve = Curve3D.new()
	
	for point in points:
		curve.add_point(Vector3(point.x * size, 0, point.y * size))

	self.curve = curve
	print(points)
	save_curve_resource(curve)


# --- Generate all points for a 2D Hilbert curve ---

func save_curve_resource(curve):
	ResourceSaver.save(curve,save_path)
	print("saved at: ", save_path)
func hilbert2d_points(order: int) -> Array:
	var points = []
	var total_points = int(pow(2, order)) ** 2

	for i in range(total_points):
		points.append(_hilbert_index_to_xy(i, order))

	return points


# --- Convert Hilbert index to 2D coordinate ---
func _hilbert_index_to_xy(index: int, order: int) -> Vector2:
	var n = int(pow(2, order))
	var x = 0
	var y = 0
	var t = index
	var s = 1

	while s < n:
		var rx = (t / 2) & 1
		var ry = (t ^ rx) & 1
		var rot_result = _rot(s, x, y, rx, ry)
		x = rot_result.x + s * rx
		y = rot_result.y + s * ry
		t = int(t / 4)
		s *= 2

	return Vector2(x, y)


# --- Rotate/flip quadrant ---
func _rot(n: int, x: int, y: int, rx: int, ry: int) -> Vector2:
	if ry == 0:
		if rx == 1:
			x = n - 1 - x
			y = n - 1 - y
		var temp = x
		x = y
		y = temp
	return Vector2(x, y)

func chamfer_points(points, size):
	if points.size() < 3: 
		return points
		
	var out_points: Array = []
	for i in range(points.size()):
		if i == 0:
			out_points.append(points[i])
			continue
		elif i == points.size() - 1:
			out_points.append(points[i])
			continue
		var prev = points[i - 1]
		var curr = points[i]
		var nxt = points[i + 1]

		var dir_to_prev = (prev - curr).normalized()
		var dir_to_next = (nxt - curr).normalized()

			# Move slightly toward prev and next to form chamfer
		var corner_in = curr + dir_to_prev * size
		var corner_out = curr + dir_to_next * size

		out_points.append(corner_in)
		out_points.append(corner_out)

	return out_points
			
		
